pipelines: 
  branches:
   staging:
    - step: 
        script:  
          - ssh apitestcoachscom@api.test.coachsome.com 'cd /srv/www/api.test.coachsome.com/www/; git pull; echo "Changes deployed!"'