version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: coachsome-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Enable xdebug
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - coachsome-network

  db:
    image: mysql:5.7
    container_name: coachsome-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - coachsome-network

  nginx:
    image: nginx:alpine
    container_name: coachsome-nginx
    restart: unless-stopped
    ports:
      - 8000:80
      # Port for xdebug (ensure this matches the remote_port in the xdebug.ini)
      - "9001:9001"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - coachsome-network

  phpmyadmin:
    container_name: coachsome-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "7000:80"
    links:
      - "db"
    environment:
      UPLOAD_LIMIT: 3000000000
    networks:
      - coachsome-network


#Docker Networks
networks:
  coachsome-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
