openapi: 3.0.3
info:
  version: 1.0.0
  title: Coachsome Api
  description: This documentaion describes all the public and protected resources.

servers:
- url: https://api.coachsome.com/api
  description: production server
- url: https://api.test.coachsome.com/api
  description: test server
- url: https://localhost:8000/api
  description: local server

components:
  parameters:
    locale:
      in: header
      name: Language-Code
      schema:
        type: string
      description: Language code is needed for every parameter.

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        roleId:
          type: integer
        password:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

paths:
  /login:
    $ref: "/swagger/paths/auth/login"
  /register:
    $ref: "/swagger/paths/auth/register"

  /profiles:
    $ref: "/swagger/paths/profile/profiles"


